name: Release & Pre-release

on:
  push:
    branches: [main]
  release:
    types:
      - created

jobs:
  release:
    uses: openmrs/openmrs-contrib-gha-workflows/.github/workflows/release-frontend-module.yml@main
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      BOT_PAT: ${{ secrets.OMRS_BOT_GH_TOKEN }}